# Generated by Django 3.1.7 on 2021-03-02 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='posts/logo')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('language', models.CharField(choices=[('python', 'python'), ('javascript', 'javascript'), ('java', 'java'), ('C++', 'C++')], max_length=60)),
                ('career', models.CharField(choices=[('신입', '신입'), ('경력', '경력')], max_length=60)),
                ('location', models.CharField(choices=[('경기도 성남시 분당구', '경기도 성남시 분당구'), ('서울특별시 강남구', '서울특별시 강남구'), ('서울특별시 서초구', '서울특별시 서초구'), ('서울특별시 동작구', '서울특별시 동작구'), ('제주특별자치도 서귀포구', '제주특별자치도 서귀포구'), ('대전광역시 유성구', '대전광역시 유성구')], max_length=60)),
                ('salary', models.CharField(max_length=60)),
                ('deadline', models.DateField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
